name: marsuseduverse
description: Your Comprehensive Islamic Learning Companion A Flutter-based mobile application delivering authentic Islamic education through

publish_to: 'none'

version: 1.1.2+4

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  youtube_player_flutter: ^9.1.3
  dio: ^5.4.0
  path_provider: ^2.1.1
  flutter_pdfview: ^1.2.7
  connectivity_plus: ^5.0.2
  http: ^1.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.10
  upgrader: ^11.3.2
  shimmer: ^3.0.0
  animated_snack_bar: ^0.4.0
  share_plus: ^7.2.1
  lottie: ^3.3.1
  package_info_plus: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
